### PR TITLE
Use same IP address for both boots and nginx

### PR DESCRIPTION
**Pull request by mrchrd**
Signed-off-by: Michael Richard <michael.richard.ing@gmail.com>

## Description

This configures NGINX to listen on port 8080 and lets go the need to configure a second IP address on the host dedicated to NGINX.

## Why is this needed

Setting up a second IP address to host NGINX on the same host is not always easy, especially when running tinkerbell on network devices like switches. The second IP address adds a useless level of complexity. In the future, all the code required to identify the host operating system and configure the IP address could even be removed and left as a prerequisite, since the host is likely to have an IP address already configured.

## How Has This Been Tested?

The untouched vagrant_test.go test ran sucessfully.

## How are existing users impacted? What migration steps/scripts do we need?

Simply re-applying the docker-compose.yml should be sufficient (untested).
Additional firewall rules to allow traffic on port 8080 could be required depending on user's network configuration.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by gianarb** [comment]
Hello!

Thank you for this work, can you rebase, please?

Thanks

**Comment by mrchrd** [comment]
Done

**Comment by gianarb** [comment]
Ops, I am sorry
This PR should fix the CI issue https://github.com/tinkerbell/sandbox/pull/44

**Comment by gianarb** [comment]
I am not sure how this will impact users that are running Nginx and I am not sure if we have to mark it as breaking change or not. I will have a look tomorrow 👍

**Comment by mrchrd** [comment]
Now it's fixed!

**Comment by mrchrd** [comment]
It's probably fair to consider it as a breaking change, even though it won't break anything in a majority of cases. Upgrading will fail if:
1) Some service is already running on port 8080
2) Firewall's blocking traffic on port 8080

**Review by gianarb — COMMENTED** [review]
I tried the migration and yes, a docker-compose rm, up does the magic! Thanks

**Review by gianarb — APPROVED** [review]

**Pull request merged**
