### PR TITLE
Convert to debian and allow passing a bridge interface

### PR DESCRIPTION
**Pull request by ClashTheBunny**
## Why is this needed

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by mmlb** [comment]
Hey @ClashTheBunny thanks for the PR. I like the bridge patch and most of the debian one too, but I don't want the change from ubuntu -> debian nor the fetching of the image in the docker-compose.yaml (no need to download if not going to be used). Can you drop those bits and instead add a section in the README about different OS images and add your debian changes there?

**Comment by mmlb** [comment]
oh wait you didn't change from ubuntu -> debian! (still haven't had my espresso :smile:)

**Comment by ClashTheBunny** [comment]
Sorry, I too have not had my coffee, this was meant to be a draft still! :-D

I'm working on the documentation for both the bridge config and how to select a different OS.  I did mistakenly include debian in the default .env file, so I do need to change that back...

**Comment by chrisdoherty4** [comment]
Closing as stale. Feel free to re-open as needed.

**Pull request closed without merging**
