### PR TITLE
provisioner setup changes to enable NAT for workers

### PR DESCRIPTION
**Pull request by Cbkhare**
## Description

Provisioner NAT setup for workers 

## Why is this needed

internet access on workers 
https://github.com/tinkerbell/sandbox/issues/31 

Fixes: #

## How Has This Been Tested?

- workflow executed successfully.
- ping from workers works correctly.

PR in reference with https://github.com/tinkerbell/tink/pull/410

### CODE REVIEW

**Review by gauravgahlot — APPROVED** [review]

**Review by gianarb — APPROVED** [review]

**Comment by gianarb** [comment]
Thank you @Cbkhare in order to close this task you also need to update the documentation 

https://docs.tinkerbell.org/setup/extending-vagrant/
"Getting Your Worker Connected to the Internet" is not needed anymore for example and as part of the Setup guide, you can remove the need to pull, tag, and push the docker.io/hello image.

**Comment by mmlb** [comment]
@Cbkhare eth0/eth1 should not have been used here right? This breaks the terraform setup as those nics won't be named ethN. We should add a config var `TINKERBELL_NETWORK_WAN` and then can do `eth0` -> `$TINKERBELL_NETWORK_WAN` and `eth1` -> `$TINKERBELL_NETWORK_INTERFACE`

**Comment by mmlb** [comment]
@gianarb and we don't need a container registry anymore either right?

**Comment by gianarb** [comment]
I think overall it is not bad to push a registry. It is already done and it gives us some flexibility. If users don't want to use it they can write their workflows using any public registry.

We still pull the tink-worker registry from the internal registry. We can probably pass the image name as kernel cmdline and get it from there (right now it is fixed in the `workflow-helper.sh` script) but I can't clearly picture a migration path in my mind yet

**Comment by gianarb** [comment]
Very right btw @Cbkhare can you have a look?

**Pull request merged**
