### PR TITLE
Fix empty docker-compose in basebox

### PR DESCRIPTION
**Pull request by mmlb**
## Description

Ensures docker-compose is correctly downloaded.
Also adds some better debuggability to setup.sh and the vagrant provision script.
A bunch of misc clean ups following the boy scout rule (leave things better than you found them)

## Why is this needed

Fixes: #59 

## How Has This Been Tested?

`vagrant up provisioner` now works

## How are existing users impacted? What migration steps/scripts do we need?

Fixes a bug where the vagrant sandbox wasn't working.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by mmlb** [comment]
Note, this PR won't actually resolve anything for 2 reasons:

1. We need to build a new basebox and update vagrant cloud and update this Vagrantfile with the new version.
2. I can't actually promise that my basebox provision.sh script actually works. I haven't been able to figure out how to get packer to correctly build my box. I'm still seeing the empty docker-compose file even when I take drastic measures to ensure vagrant uses my built box.

**Comment by mmlb** [comment]
Here's what I'm seeing (some extra debugging thrown into provision.sh for ... debugging):
```
==> vagrant-libvirt: + setup_docker_compose
==> vagrant-libvirt: + which docker-compose
==> vagrant-libvirt: + :
==> vagrant-libvirt: + ls -l /usr/local/bin/docker-compose
==> vagrant-libvirt: ls: cannot access '/usr/local/bin/docker-compose': No such file or directory
==> vagrant-libvirt: + :
==> vagrant-libvirt: + local name url
==> vagrant-libvirt: ++ uname -s
==> vagrant-libvirt: ++ uname -m
==> vagrant-libvirt: + name=docker-compose-Linux-x86_64
==> vagrant-libvirt: + url=https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64
==> vagrant-libvirt: + curl -fsSLO https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64
==> vagrant-libvirt: + curl -fsSLO https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64.sha256
==> vagrant-libvirt: + sha256sum -c
    vagrant-libvirt: docker-compose-Linux-x86_64: OK
==> vagrant-libvirt: + rm -f docker-compose-Linux-x86_64.sha256
==> vagrant-libvirt: + chmod +x docker-compose-Linux-x86_64
==> vagrant-libvirt: + sudo mv docker-compose-Linux-x86_64 /usr/local/bin/docker-compose
==> vagrant-libvirt: + docker-compose -h
    vagrant-libvirt: Define and run multi-container applications with Docker.
    vagrant-libvirt:
    vagrant-libvirt: Usage:
    vagrant-libvirt:   docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
    vagrant-libvirt:   docker-compose -h|--help
    vagrant-libvirt:
    vagrant-libvirt: Options:
    vagrant-libvirt:   -f, --file FILE             Specify an alternate compose file
    vagrant-libvirt:                               (default: docker-compose.yml)
    vagrant-libvirt:   -p, --project-name NAME     Specify an alternate project name
    vagrant-libvirt:                               (default: directory name)
    vagrant-libvirt:   -c, --context NAME          Specify a context name
    vagrant-libvirt:   --verbose                   Show more output
    vagrant-libvirt:   --log-level LEVEL           Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    vagrant-libvirt:   --no-ansi                   Do not print ANSI control characters
    vagrant-libvirt:   -v, --version               Print version and exit
    vagrant-libvirt:   -H, --host HOST             Daemon socket to connect to
    vagrant-libvirt:
    vagrant-libvirt:   --tls                       Use TLS; implied by --tlsverify
    vagrant-libvirt:   --tlscacert CA_PATH         Trust certs signed only by this CA
    vagrant-libvirt:   --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
    vagrant-libvirt:   --tlskey TLS_KEY_PATH       Path to TLS key file
    vagrant-libvirt:   --tlsverify                 Use TLS and verify the remote
    vagrant-libvirt:   --skip-hostname-check       Don't check the daemon's hostname against the
    vagrant-libvirt:                               name specified in the client certificate
    vagrant-libvirt:   --project-directory PATH    Specify an alternate working directory
    vagrant-libvirt:                               (default: the path of the Compose file)
    vagrant-libvirt:   --compatibility             If set, Compose will attempt to convert keys
    vagrant-libvirt:                               in v3 files to their non-Swarm equivalent
    vagrant-libvirt:   --env-file PATH             Specify an alternate environment file
    vagrant-libvirt:
    vagrant-libvirt: Commands:
    vagrant-libvirt:   build              Build or rebuild services
    vagrant-libvirt:   config             Validate and view the Compose file
    vagrant-libvirt:   create             Create services
    vagrant-libvirt:   down               Stop and remove containers, networks, images, and volumes
    vagrant-libvirt:   events             Receive real time events from containers
    vagrant-libvirt:   exec               Execute a command in a running container
    vagrant-libvirt:   help               Get help on a command
    vagrant-libvirt:   images             List images
    vagrant-libvirt:   kill               Kill containers
    vagrant-libvirt:   logs               View output from containers
    vagrant-libvirt:   pause              Pause services
    vagrant-libvirt:   port               Print the public port for a port binding
    vagrant-libvirt:   ps                 List containers
    vagrant-libvirt:   pull               Pull service images
    vagrant-libvirt:   push               Push service images
    vagrant-libvirt:   restart            Restart services
    vagrant-libvirt:   rm                 Remove stopped containers
    vagrant-libvirt:   run                Run a one-off command
    vagrant-libvirt:   scale              Set number of containers for a service
    vagrant-libvirt:   start              Start services
    vagrant-libvirt:   stop               Stop services
    vagrant-libvirt:   top                Display the running processes
    vagrant-libvirt:   unpause            Unpause services
    vagrant-libvirt:   up                 Create and start containers
    vagrant-libvirt:   version            Show the Docker-Compose version information
==> vagrant-libvirt: + which docker-compose
    vagrant-libvirt: /usr/local/bin/docker-compose
==> vagrant-libvirt: + ls -l /usr/local/bin/docker-compose
    vagrant-libvirt: -rwxrwxr-x 1 vagrant vagrant 12254032 Apr 27 20:51 /usr/local/bin/docker-compose
```
from the packer build but vagrant up still fails :sob: 
```
    provisioner: + check_command docker-compose
    provisioner: + command_exists docker-compose
    provisioner: + command -v docker-compose
    provisioner: ++ which docker-compose
    provisioner: + [[ -s /usr/local/bin/docker-compose ]]
    provisioner: + echo 'ERROR: Prerequisite command not installed: docker-compose'
    provisioner: ERROR: Prerequisite command not installed: docker-compose
    provisioner: + return 1
    provisioner: + failed=1
```
(I added a check to command_exists to check the size > 0)

The steps I've done is basically:
```
vagrant box remove $(vagrant box list | awk '{print $1}')
sudo virsh vol-list default |awk '/.img/ {print $1}' | xargs sudo virsh vol-delete --pool default %
git clean -fxd
packer build --parallel-builds=1 template.json
vagrant box add develop output-vagrant-libvirt/package.box
vagrant destroy -f; vagrant up --provision --no-destroy-on-error provisioner
````
Note:  yes I changed the sandbox's Vagrantfile's box to just `develop` *just to make sure it doesn't pull from vagrant cloud*

Can some one please try to reproduce or point out what I'm doing wrong?

**Comment by gianarb** [comment]
I tried this PR with Vagrant+Virtualbox and it works.
I mentioned multiple times the e2e test on sandbox runs on Vagrant+Virtualbox, so my feeling is that it is a libvirt specific problem. I opened this issue to see if we can get libvirt in our self hosted runners to run the test twice, with libvirt as well https://github.com/tinkerbell/infrastructure/issues/10

**Comment by mmlb** [comment]
@gianarb looks like the vagrant test is failing because of port conflict. Is there a vagrant guest still running on the box maybe?

**Comment by mmlb** [comment]
@gianarb / @nshalman PTAL

**Comment by nshalman** [comment]
@mmlb at this point is the `sync` the only major functionality change to fix the underlying issue, where the rest is all cleanup?

**Comment by mmlb** [comment]
@nshalman yep

**Comment by nshalman** [comment]
I have tested this and it worked for me.

Manual changes:
```diff
diff --git a/deploy/vagrant/Vagrantfile b/deploy/vagrant/Vagrantfile
index 61624ff..8a24ef7 100644
--- a/deploy/vagrant/Vagrantfile
+++ b/deploy/vagrant/Vagrantfile
@@ -25,8 +25,7 @@ end
 Vagrant.configure('2') do |config|

   config.vm.define :provisioner do |provisioner|
-    provisioner.vm.box = "tinkerbelloss/sandbox-ubuntu1804"
-    provisioner.vm.box_version = "0.1.0"
+    provisioner.vm.box = "develop"
     provisioner.vm.hostname = 'provisioner'
     provisioner.vm.synced_folder './../../', '/vagrant'
     provisioner.vm.provision :shell,
```

Commands run
```
[nix-shell:~/sandbox/deploy/vagrant/basebox/ubuntu1804]
$ packer build --parallel-builds=1 template.json
...
[nix-shell:~/sandbox/deploy/vagrant/basebox/ubuntu1804]
$ vagrant box add develop output-vagrant-libvirt/package.box
...
[nix-shell:~/sandbox/deploy/vagrant]
$ vagrant destroy -f; vagrant up --provision --no-destroy-on-error provisioner
```

**Review by nshalman — APPROVED** [review]

**Review by gianarb — APPROVED** [review]

**Pull request merged**
