### PR TITLE
Remove the CA certificate from bundle

### PR DESCRIPTION
**Pull request by rgl**
## Description

See https://github.com/tinkerbell/sandbox/issues/105

I also took the opportunity to:

1. use a different csr for the tinkerbell ca (this allows us to clearly identify the ca and server certificates)
2. switch from rsa to ecdsa (its equally safer and its generally faster)
3. modify tls-gen to also copy the ca certificate to the workflow directory (this simplifies the compose file)
4. Configure the vagrant environment to trust the tinkerbell CA. 
5. Configure the vagrant environment root and vagrant accounts to automatically login into the registry. 

## Why is this needed

See https://github.com/tinkerbell/sandbox/issues/105

Fixes: #105

## How Has This Been Tested?

Tested locally by starting Tinkerbell with compose and vagrant.

## How are existing users impacted? What migration steps/scripts do we need?

Should not be impacted.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by jacobweinstock** [comment]
hmmm....I wasn't able to get this PR working. Let me get some notes together for what I ran into.

**Comment by jacobweinstock** [comment]
Hey @rgl, thanks for the update. `vagrant up` is now working for me. I apologize but I'm not fully understanding what this PR or #105 are trying to resolve. 

This branch and the existing mainline branch both behave the same for me in terms of pushing to the local container registry and `curl https://192.168.50.4/v2/_catalog`. 

I get the following output from both this PR and main.

```bash
vagrant@ubuntu2004:~$ docker tag hello-world 192.168.50.4/hello-world
vagrant@ubuntu2004:~$ docker push 192.168.50.4/hello-world
Using default tag: latest
The push refers to repository [192.168.50.4/hello-world]
Get "https://192.168.50.4/v2/": x509: certificate signed by unknown authority
---
vagrant@ubuntu2004:~$ curl https://192.168.50.4/v2/_catalog
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
---
vagrant@ubuntu2004:~$ curl https://192.168.50.4/v2/_catalog -k
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
---
```

Also, for this PR the initial `vagrant up` is successful but shows this:

```bash
==> provisioner: Running provisioner: Trust the Tinkerbell CA (shell)...
    provisioner: Running: script: Trust the Tinkerbell CA
    provisioner: /tmp/vagrant-shell: line 2: docker-compose: command not found
    provisioner: Updating certificates in /etc/ssl/certs...
    provisioner: 0 added, 0 removed; done.
    provisioner: Running hooks in /etc/ca-certificates/update.d...
    provisioner: done.
```
```

**Comment by rgl** [comment]
> Hey @rgl, thanks! this is working for me. Would it be possible to move this setup out of the Vagrantfile so that other infrastructure providers like Terraform can consume it? Finding a way to allow docker-compose only consumers to use this would also be ideal. Maybe a new directory for host scripts? Just a brainstorming idea.

You mean to move it to a script file at `deploy/host/trust-tinkerbell-ca-and-restart-docker.sh`?

Note that the script will modify the host configuration using `sudo`, and it assumes the host is running Ubuntu and the systemd `docker` service exists. If that's fine, I can do that.

> I apologize that it's not well documented but the design philosophy here is:
> 
> "_Vagrant and Terraform are now only responsible for standing up infrastructure and then running docker-compose, not for running any glue scripts. The compose calls single-shot services to do all the glue required to get a fully functional Tinkerbell stack._" ref: [here](https://github.com/tinkerbell/sandbox/pull/90)

Can `docker-compose.yml` run scripts in the host?

**Comment by rgl** [comment]
@jacobweinstock, ping? :-)

**Comment by jacobweinstock** [comment]
Hey @rgl, really sorry for the delayed response. 

_You mean to move it to a script file at deploy/host/trust-tinkerbell-ca-and-restart-docker.sh?_
That's an option. What do you think? The design idea for this repo is to keep concise as possible layers between what handles 

- infrastructure stand up
  - vagrant, terraform, etc
- Tinkerbell stand up
  - the glue required to get a fully functional Tinkerbell stack

I don't know if there's a clean way to handle this. The code added to the Vagrantfile is portable to Terraform right now. So Terraform users arent able to take advantage of this TLS update.

**Comment by rgl** [comment]
@jacobweinstock, I've refactored the code into deploy/compose/tls/trust.sh which is now shared between Vagrant and Terraform.

**Comment by rgl** [comment]
@jacobweinstock, I've refactored the code into deploy/compose/tls/trust.sh which is now shared between Vagrant and Terraform.

Please check it again.

**Review by jacobweinstock — APPROVED** [review]
Thanks for your patience and pushing this through!

**Pull request merged**
