### PR TITLE
Push binaries as release artifact

### PR DESCRIPTION
**Pull request by gianarb**
We want to get all the binaries pushed as artifact when a new sandbox gets
released.

Done: CLI command capable of reading multi arch manifest from a registry,
getting the layer where the binary is located and copy it to a specific
directory.

TODO:

- [ ] Hook it up as github action for all the projects when sandbox gets released
  (push a new tag)

### CODE REVIEW

**Comment by mmlb** [comment]
:D I actually want to go the other way around, build the binaries use them in the Dockerfiles and then we can also push to github release. But don't have anything to show so this is good too :D

**Comment by mmlb** [comment]
Oh nm, I just noticed this was sandbox not tink!

**Comment by gianarb** [comment]
Yep this is a sandbox and I am not speaking about the development environment, that's a thing I don't care about, everybody has its own way of working and I love that.

What I am trying to solve with this is the release cycle. It uses containers because it is what currently all the components are releasing.

It currently assumes that the image is a multi-arch image, with the last layer being the one that copies the binary in `/usr/bin`. As long as those requirements are consistent it is not a problem how images get built in the various project or how the maintainers want to work on them. I know people prefer to start a Kubernetes cluster 🦀

**Comment by mmlb** [comment]
Yep it makes sense to pick out the binaries from the "official" container images.

**Review by mmlb — APPROVED** [review]

**Comment by gianarb** [comment]
This is my fork, but we have binaries 👍 

Screenshot 2020-11-19 at 11 24 18

**Pull request merged**
