### PR TITLE
[WIP] Update sandbox for latest changes

### PR DESCRIPTION
**Pull request by detiber**
## Description

Update sandbox for latest Tinkerbell chagnes

## Why is this needed

The last sandbox release is getting quite a bit old at v0.6.0, with all the changes that have landed since then, it's about time for a v0.7.0 release

## How Has This Been Tested?

TODO

## How are existing users impacted? What migration steps/scripts do we need?

TODO

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

## Blockers:

 - [x] https://github.com/tinkerbell/tink/pull/604
 - [ ] https://github.com/tinkerbell/tink/pull/603
 - [ ] https://github.com/tinkerbell/hegel/pull/80
 - [ ] Tagged semver release for boots
 - [ ] Tagged semver release for tink
 - [ ] Tagged semver release for hegel

### CODE REVIEW

**Comment by mmlb** [comment]
I'd like to see the next release be w/o tls which is still in progress in tink. I think it makes sense to wait until then instead of release 0.7 and come up with 0.8 soon after (hopefully).

**Comment by displague** [comment]
Getting the dependencies tagged first sounds like the right order to me. Sandbox is then built on well-known, fixed, dependencies.

**Comment by chrisdoherty4** [comment]
0.7 has been released with lots of updates. This issue can be closed.

**Comment by chrisdoherty4** [comment]
This is outdated and will likely change as we continue moving to Kube backend only.

**Pull request closed without merging**
